---

- name: Clone drupal
  sudo: yes
  git:
    repo: "{{ drupal.git_repo }}"
    dest: /var/www/drupal
    version: "{{ drupal.git_version }}"

- name: Install drupal
  sudo: yes
  command: drush -y si {{ drupal.install_profile }} --db-url=mysql://{{ drupal.database_username}}:{{ drupal.database_password }}@{{ mysql_host }}/{{ drupal.database }} --account-pass={{ drupal.admin_password }}
  args:
    chdir: "/var/www/drupal/{{ drupal.docroot }}"
    creates: "/var/www/drupal/{{ drupal.docroot }}/sites/default/settings.php"

- name: Enable modules
  sudo: yes
  command: drush -y pm-enable {{ item }}
  args:
    chdir: "/var/www/drupal/{{ drupal.docroot }}"
  with_items: drupal.install_modules

- name: Disable modules
  sudo: yes
  command: drush -y pm-disable {{ item }}
  args:
    chdir: "/var/www/drupal/{{ drupal.docroot }}"
  with_items: drupal.uninstall_modules

- name: Uninstall modules
  sudo: yes
  command: drush -y pm-uninstall {{ item }}
  args:
    chdir: "/var/www/drupal/{{ drupal.docroot }}"
  with_items: drupal.uninstall_modules

# - name: Set simple drupal variables
#   sudo: yes
#   command: drush -y vset {{ item.name }} {{ item.value }}
#   with_items: drupal.set_variables
#   args:
#     chdir: "/var/www/drupal/{{ drupal.docroot }}"

# - name: Set complex drupal variables
#   sudo: yes
#   shell: "php -r \"print json_encode({{ item.value }});\" | drush vset --format=json {{ item.name }} -"
#   with_items: drupal.set_variables_array
#   args:
#     chdir: "/var/www/drupal/{{ drupal.docroot }}"

- name: Update files directory owner settings
  sudo: yes
  command: "chown -R root:www-data /var/www/drupal/{{ drupal.docroot }}/sites/default/settings.php"

- name: Update files directory permissions settings
  sudo: yes
  command: "chmod -R u-x+rwX,g-x+rwsX,o-x+rX /var/www/drupal/{{ drupal.docroot }}/sites/default/settings.php"

- name: Create apache site
  sudo: yes
  template:
    src: drupal.conf.j2
    dest: /etc/apache2/sites-available/drupal.conf

- name: Disable default apache site
  sudo: yes
  command: a2dissite 000-default

- name: Enable drupal apache site
  sudo: yes
  command: a2ensite drupal
  notify: restart apache
